name: Build Auto Totem Shield

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Java 25
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '25'
          cache: gradle

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '9.7.0'

      - name: Build
        run: gradle build

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: AutoTotemShield-26.1.2
          path: build/libs/*.jar
